# Use OpenJDK base image
FROM openjdk:17-jdk-slim

# Add jar file to the container
ARG JAR_FILE=target/taskmanagement-0.0.1-SNAPSHOT.jar
COPY ${JAR_FILE} app.jar

# Run the jar file
ENTRYPOINT ["java", "-jar", "/app.jar"]
